// /app/layout.tsx

import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/provider/modal-provider";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/provider/auth-provider"; // 수정된 AuthProvider
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth"; // next-auth 설정 경로

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions as any); // 서버에서 세션 가져오기

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider session={session}>
          <ModalProvider />
          {children}
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
