import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/provider/modal-provider";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/provider/auth-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { VisitorTracker } from "@/components/visitor-tracker";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "format-detection": "email=no",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
  userScalable: false,
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions as any);

  return (
    <html lang="en">
      <head />
      <body className={`${inter.className} md:h-[100dvh]`}>
        <AuthProvider session={session}>
          <ModalProvider />
          <VisitorTracker />
          {children}
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
