ALTER TABLE careservicerequest
MODIFY COLUMN status ENUM(
  'PENDING',
  'PENDING_OWNER_APPROVAL',
  'SCHEDULED',
  'IN_PROGRESS',
  'AWAITING_TENANT_CONFIRMATION',
  'COMPLETED',
  'CANCELLED'
) NOT NULL DEFAULT 'PENDING';
