-- AlterTable
ALTER TABLE `careservicerequest` MODIFY COLUMN `status` ENUM('PENDING','PENDING_OWNER_APPROVAL','SCHEDULED','IN_PROGRESS','AWAITING_TENANT_CONFIRMATION','PENDING_STAFF_REVIEW','COMPLETED','CANCELLED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `approvedByRole` VARCHAR(191) NULL,
    ADD COLUMN `approvedByUserId` INT NULL,
    ADD COLUMN `completionNote` TEXT NULL,
    ADD COLUMN `completionProofUrl` VARCHAR(191) NULL;
