-- AlterTable: ContractDraftStatus enum에 REJECTED 추가
ALTER TABLE `contract_draft` MODIFY COLUMN `status` ENUM('DRAFT','UNDER_LANDLORD_REVIEW','SENT_TO_TENANT','REVISION_REQUESTED','APPROVED','FINALIZED','REJECTED') NOT NULL DEFAULT 'DRAFT';
